# Generated by Django 5.0.1 on 2024-01-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'граммы'), ('pcs', 'штуки'), ('l', 'литры')], default='g', max_length=10),
        ),
    ]
