# Generated by Django 5.0.1 on 2024-01-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_product_quantity_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='used_count',
            new_name='recipe_count',
        ),
    ]
