# Generated by Django 5.0.1 on 2024-01-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_used_count_product_recipe_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeproduct',
            name='weight',
        ),
        migrations.AddField(
            model_name='recipeproduct',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
